engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  eslint:
    enabled: false
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
ratings:
  paths:
   - "includes/*"
exclude_paths:
- "includes/api/cocart/v1/"
- "includes/api/legacy/"
- "languages/"
